language: python
python: 
  - "3.6"

#install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

#run tests
script: 
  - py.test --cov=app
after_success:
  - coveralls
